version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - node --version
      - yarn set version berry
      - yarn set version latest
      - yarn install
  build:
    commands:
      - yarn build

artifacts:
  base-directory: build
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
