version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 12.18.3
      - yarn install --immutable --immutable-cache --check-cache
  build:
    commands:
      - yarn cdk synth

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
