version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn set version berry
      - yarn install
  build:
    commands:
      - yarn cdk synth

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'
