version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - n 12.18.3
      - yarn install
  build:
    commands:
      - mkdir .server
      - cp -rfv $CODEBUILD_SRC_DIR_assets ./build
      - yarn build:server
      - yarn package:server
artifacts:
  base-directory: .server
  files:
    - '**/*'

cache:
  paths:
    - 'node_modules/**/*'